[package]
name = "helgoboss-license-api"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"
publish = false

[dependencies]
serde = "1"
validator = { version = "0.16.1", features = ["derive"] }