[package]
name = "realearn-dialogs"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"
publish = false

[dependencies]
derive_more.workspace = true
indexmap.workspace = true