[package]
name = "realearn-csi"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"
publish = false

[dependencies]
nom.workspace = true
helgoboss-midi.workspace = true
base.workspace = true
realearn-api.workspace = true
derive_more.workspace = true