[package]
name = "rx-util"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

[dependencies]
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
